### ISSUE TITLE
Bug: QuaternionConverter is adding itself to a list of converters many times

### ISSUE THREAD

**Issue by EpsilonD3lta** [applejag/Newtonsoft.Json-for-Unity.Converters#89] opened 2024-01-08 15:56 UTC
## Expected behavior

One QuaternionConverter in a list of QuaternionConverters in UnityEngine.Math

## Actual behavior

Many QuaternionConverters
![image](https://github.com/applejag/Newtonsoft.Json-for-Unity.Converters/assets/30054007/1e76ca58-a04c-422c-88c4-546e83970f05)

## Steps to reproduce
- Not sure, probably recompilation ads it?

## Details
- Windows 10
- Android build target
- Package version 1.6.0
- Unity 2022.3.0f1

**Comment by EpsilonD3lta** [comment] 2024-01-08 16:06
I have noticed that there is not Mathematics.QuaternionConverter in the list (at least in my case), maybe it is related

**Comment by applejag** [comment] 2024-01-08 16:14
Hmm. Curious. Thanks @EpsilonD3lta for reporting this.

What if you update to 1.6.2 that was released today?

If it persists, a workaround could be to reset the config by deleting the file in Assets/Resources/

**Comment by EpsilonD3lta** [comment] 2024-01-08 16:25
Well I can reset it (I reset the changes in version control) but it keeps adding itself again.

However, it seems that the new version fixed it. What a nice coincidence :) . I checked the update, but I had package manager open for few hours and the update was not visible until I manually refreshed.

**Comment by applejag** [comment] 2024-01-08 16:30
Nice!

This issue might pop up with future types, but until then I'm just going to close this issue as resolved.

Could be investigated to find the root cause, but I'm more leaning towards "only fix it when it's broken"

**Closed by applejag** 2024-01-08 16:30 UTC
Labels: bug
